### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by rs1990** [Swarm-IITKgp/singleRobot#8]
Hello i keep getting this error while running a catkin_make on indigo. any help please??

CMake Error at gazebo_ros_pkgs/gazebo_ros/CMakeLists.txt:26 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

```
gazeboConfig.cmake
gazebo-config.cmake
```

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by sam17** [comment]
Did you install ros-gazebo?

Use `sudo apt-get install ros-indigo-gazebo-ros`

**Comment by rs1990** [comment]
hey yup i got that. i had the wrong version installed. Thanks a lot but when i try to Generate the launch file for the singlerobot package for n-agents

roscd singlerobot
bash generator.sh <number of agents> i get this error ...

generator.sh: line 3: launch/singlerobot.launch: No such file or directory

**Comment by sam17** [comment]
Readme Updated
